[package]
name = "aura-common"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
memmap2 = { workspace = true }
crossbeam-epoch = { workspace = true }
thiserror = { workspace = true }
crc32fast = { workspace = true }
libc = { workspace = true }
bytemuck = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
