[package]
name = "aura-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
aura-common = { path = "../aura-common" }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
memmap2 = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
